### ISSUE TITLE
grunt server error

### ISSUE THREAD

**Issue by twilly86** [ghinda/bizcardmaker#2]
I am getting the following error when i try and build locally...

grunt server
Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "deploy.json" file (Error code: ENOENT).
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.

**Comment by ghinda** [comment]
Create a `deploy.json` file with:

```
{
  "cloudflare": {
    "key": "",
    "email": "",
    "zone": ""
  }
}
```

Should do it.
