### ISSUE TITLE
I want all photos to be circular, so I have to fix some parts

### ISSUE THREAD

**Issue by huantransuper** [ghinda/bizcardmaker#3]

**Comment by ghinda** [comment]
You can have rounded photos by using transparent PNGs. Here's a sample:
![bizcardmaker-com-theme-picture--space-full](https://user-images.githubusercontent.com/325171/61609054-9009ad00-ac5d-11e9-8a25-96b02f6ba30a.jpg)

**Comment by huantransuper** [comment]
Will I have to use pre-rounded photos? The image you want to upload will be rounded up

**Comment by huantransuper** [comment]
![Screenshot from 2019-07-28 00-40-56](https://user-images.githubusercontent.com/41030688/61997734-6f63ac00-b0d0-11e9-90e7-3c50b274d414.png)
I want to choose the image, it will become like the picture

**Comment by ghinda** [comment]
Yes, you'll need a pre-rounded transparent png.
